transition_condition(machine_state(0, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(1, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(1, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(2, 0, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(2, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(3, A_register, B_register, C_register, D_register, [A_register|Stack], Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(3, A_register, B_register, C_register, D_register, [], Inputstack, Outputstack, Memory, 0, 0), machine_state(3, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 1, 0)).
transition_condition(machine_state(3, A_register, B_register, C_register, D_register, [0|Stack], [ValueRead|Inputstack], Outputstack, Memory, 0, 0), machine_state(4, A_register, B_register, C_register, D_register, [ValueRead|Stack], Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(3, A_register, B_register, C_register, D_register, [1,WriteValue|Stack], Inputstack, Outputstack, Memory, 0, 0), machine_state(4, A_register, B_register, C_register, D_register, Stack, Inputstack, [WriteValue|Outputstack], Memory, 0, 0)).
transition_condition(machine_state(3, A_register, B_register, C_register, D_register, [1], Inputstack, Outputstack, Memory, 0, 0), machine_state(3, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 1, 0)).
transition_condition(machine_state(4, A_register, B_register, C_register, D_register, [PoppedValue|Stack], Inputstack, Outputstack, Memory, 0, 0), machine_state(5, A_register, B_register, PoppedValue, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(4, A_register, B_register, C_register, D_register, [], Inputstack, Outputstack, Memory, 0, 0), machine_state(4, A_register, B_register, C_register, D_register, [], Inputstack, Outputstack, Memory, 1, 0)).
transition_condition(machine_state(5, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(6, A_register, B_register, C_register, 1, Stack, Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(6, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(7, A_register, B_register, Calculated, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0)) :- Calculated #= C_register + D_register.
transition_condition(machine_state(7, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(8, A_register, B_register, C_register, D_register, [C_register|Stack], Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(8, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(9, 1, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(9, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(10, A_register, B_register, C_register, D_register, [A_register|Stack], Inputstack, Outputstack, Memory, 0, 0)).
transition_condition(machine_state(10, A_register, B_register, C_register, D_register, [], Inputstack, Outputstack, Memory, 0, 0), machine_state(10, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 1, 0)).
transition_condition(machine_state(10, A_register, B_register, C_register, D_register, [0|Stack], [ValueRead|Inputstack], Outputstack, Memory, 0, 0), machine_state(11, A_register, B_register, C_register, D_register, [ValueRead|Stack], Inputstack, Outputstack, Memory, 0, 0)).
%                    machine_state(10,          1,          0,     _23020,          1, [1, _23020],              _22796, [], init_array(0), 0, 0)
transition_condition(machine_state(10, A_register, B_register, C_register, D_register, [1,WriteValue|Stack], Inputstack, Outputstack, Memory, 0, 0), machine_state(11, A_register, B_register, C_register, D_register, Stack, Inputstack, [WriteValue|Outputstack], Memory, 0, 0)).
transition_condition(machine_state(10, A_register, B_register, C_register, D_register, [1], Inputstack, Outputstack, Memory, 0, 0), machine_state(10, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 1, 0)).
transition_condition(machine_state(11, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 0), machine_state(11, A_register, B_register, C_register, D_register, Stack, Inputstack, Outputstack, Memory, 0, 1)).
